### ISSUE TITLE
How to select multiple dates

### ISSUE THREAD

**Issue by P-Henoch** [twinssbc/Ionic2-Calendar#135]
I would like to know if it's possible to select multiple dates and how can I do it. I didn't see anything in the documentation or previous issues.

**Comment by Astacius** [comment]
you can make it on your own easily

**Comment by twinssbc** [comment]
@P-Henoch How do you want to select multiple dates? Hold and move your finger? But it will conflict with the swipe gesture. 
Suppose you want to select multiple dates by several clicks, you could record your clicked date. Since the calendar itself only highlight the current selected date. You could use a custom template to your recorded clicks.
