### ISSUE TITLE
Condensed month view?

### ISSUE THREAD

**Issue by jordanpurinton** [twinssbc/Ionic2-Calendar#149]
I really like the month view and how easy it is to customize the various templates, however, I find that it would be much nicer to be able to set the amount of weeks that you can view in month view. 

I realize that you have a week view, but I find that view to be too condensed and difficult to parse through things. 

![capture](https://user-images.githubusercontent.com/12102971/28142731-8a3c683e-671f-11e7-9667-8f4ac0f5417e.PNG)

This is what my month view looks like, but I feel as though it would be nice to have a view similar to this, but instead it only shows two weeks, and the elements in view are just larger.

Is there any functionality in this already to do something similar to this, or are there any plans to do this?

**Comment by twinssbc** [comment]
@jordanpurinton There's no functionality to control the number of weeks to be displayed in the month view. Because it's not just about changing the layout, you also need to sort out the navigation. How do you want to view the other hidden weeks in the month. Different people may have different opinion to achieve that.

Regarding the condensed week view, you don't have to display all events in the weekview. You could only display at most two events so that each event can be easily seen, if there are more than 2 weeks, you could use some other way like clicking a "more" button to navigate to a more detailed list.

**Comment by jordanpurinton** [comment]
@twinssbc thank you and again, wonderful component you've built here.

**Comment by waleedshkt** [comment]
@jordanpurinton , @twinssbc ,

Can you guys please provide me the default template for the month view?

@jordanpurinton , I am almost trying to achieve what you have accomplished already in month view: displaying events' tags in each view item. as shown in image below:

Your input would be very appreciated!
[https://github.com/waleedshkt/Ionic2-calender/blob/master/mock.jpg](url)

**Comment by jordanpurinton** [comment]
@waleedshkt so there is already documentation on the main page on how to manage templates. Take a look at that first and see how far you can get and then I can attempt to help.
