### ISSUE TITLE
Performance on Android 5.x devices (week swipe)

### ISSUE THREAD

**Issue by ericyuTestrite** [twinssbc/Ionic2-Calendar#15]
It runs well on iOS devices, but not in non-modern Androids, especially on the sliding weeks. Is there  any workaround can improve it?

**Comment by twinssbc** [comment]
@ericyuTestrite I'd like to understand what kind of performance issue you made?
Previously, in the Ionic1 version, I notice that there's some latency during the swipe, it's because the page needs to render the swipe animation and calculate the event placement at the same time. So I added some timeout in the code to solve the problem.
In this Ionic2 version, I didn't encounter such latency during the swipe, so I removed that timeout logic.

Is this kind of latency you are experiencing?
Or any latency on rendering the events? Did you only pass the events happen on one week to the calendar or all events?

**Comment by ericyu76** [comment]
Thank you for your quick reply.
I tested it using Samsung Note3 (Android 5.0.x) by demo html (week mode without load events), when swipe on the week will got about 1 sec latency until the week# changed. 
I will do more analysis on it and provide more detail information.

**Comment by twinssbc** [comment]
Yes, I notice that now.
It probably also related to this error in the Dev mode which indicates that the the viewTitle change is in a different digest cycle.

EXCEPTION: Error in ./HomePage class HomePage - inline template:2:15 caused by: Expression has changed after it was checked. Previous value: 'October 2016'. Current value: 'October 2016, Week 40'.

**Comment by ericyuTestrite** [comment]
I did a testing movie (on Android 5.1) as below. From week 50 to week 49, it take about 4 seconds. And the screen freeze during latency.

[IMG_8417.mp4.zip](https://github.com/twinssbc/Ionic2-Calendar/files/582335/IMG_8417.mp4.zip)
