### ISSUE TITLE
How can I control de swipe function trigger.

### ISSUE THREAD

**Issue by fredorlima** [twinssbc/Ionic2-Calendar#189]
In my application I need control blocks of events generated dynamically, and chage the title bar content. Is there any way to push new items in eventSource after the swipe (using this specifc date - daily view)?

**Comment by twinssbc** [comment]
@fredlima87 It seems your question is not related to the issue title?
To control the swipe function dynamically, you could set the curre**n**tDate variable to previous/next day.
To load the events after the swipe, you could set **queryMode** to ‘remote’ and add logic in **onRangeChanged** method. If you need to directly push items in eventSource, instead of replacing the whole variable, you could call **loadEvents** instance method to force refresh the calendar.
You could find more details in README.
