### ISSUE TITLE
Change dayView "day" by clicking on monthView "date" programmatically.

### ISSUE THREAD

**Issue by darkholiday** [twinssbc/Ionic2-Calendar#207]
i am using monthView and dayView in the same UI and i would like to do this:
when i select a date on the monthView calendar => the dayView scroll to that date programmatically .
i included a picture so my question will be clear enough :D
i just need some tips and i will do the rest.

![untitled](https://user-images.githubusercontent.com/10091953/31712908-5ec2cf82-b3f4-11e7-8ffd-627e48be3564.png)

**Comment by twinssbc** [comment]
@darkholiday Because of some bug of the ion-slides, I don't think two calendar work well in the same page, at least the swiping on the second calendar doesn't work.
Anyway, to control the dayview to navigate to a certain date is quite simple, you just need to set the currentDate to the specified date.

**Comment by darkholiday** [comment]
Finally i did it XD
Thank you for the tip it helped me a lot.
if someone needs some help concerning this functionality PM me.

**Comment by jayzyaj** [comment]
@darkholiday How did u do it programmatically to navigate to the previous or nextmonth?

**Comment by twinssbc** [comment]
@jayzyaj Check the **Common Questions** section in README.
