### ISSUE TITLE
After swiping to the next month, the same day becomes selected but onTimeSelected() did not trigger

### ISSUE THREAD

**Issue by chanphillip** [twinssbc/Ionic2-Calendar#21]
In month view, is it normal when the month is changed, the same day becomes highlighted?
For example, it is selecting 10 May, after swipe and jump to June, 10 June will be highlighted. But onTimeSelected() did not trigger.

**Comment by twinssbc** [comment]
This seems to be a bug. I will add the logic to trigger onTimeSelected.

**Comment by chanphillip** [comment]
I realized it also does not trigger onTimeSelected() when first loaded.

**Comment by twinssbc** [comment]
@chanphillip I'm working on this fix. I'd like to know how are you going to use onTimeSelected callback? Because I found onTimeSelected callback can be added to two places, and they can result into different results.
The current sequence is:
1. swiping to the next month, the next month dates get displayed
2. events get loaded asynchronously
3. events get rendered into the proper position in the calendar

I can add the callback either before or after the events being loaded. The events argument in the onTimeSelected callback could be either empty or having values.

**Comment by chanphillip** [comment]
@twinssbc In my case, I'm setting queryMode to be "remote" and handling onRangeChanged for loading the events asynchronously.

I think no matter if onTimeSelected is called before the events being loaded, it should be called after the events being loaded.
So by the way, wonder if this will be handled in the same way if queryMode is "remote"?

**Comment by twinssbc** [comment]
@chanphillip I have published version 0.0.14 which includes this fix. Could you have a try? Thanks.

**Comment by chanphillip** [comment]
@twinssbc I just tested it and I got an error message whenever I modify the variables which involve data binding in onCalendarTimeSelected.

> Expression has changed after it was checked.

Don't know if it is a bug or my problem as I've recently upgraded my angular & typescript.
I found a workaround which is adding setTimeout in onCalendarTimeSelected and then it works like a charm.

**Comment by twinssbc** [comment]
@chanphillip I modified some EventEmitter to use async emit, so you don't need to use setTimeout workaround now. The latest version is 0.0.15. Could you have a try? Thanks.

**Comment by chanphillip** [comment]
@twinssbc It's working perfectly! Thanks.
I'm closing this issue then.
