### ISSUE TITLE
calendar does not swiping

### ISSUE THREAD

**Issue by Hermiona** [twinssbc/Ionic2-Calendar#214]
After I updated my ionic-angular packages, the calendar stopped to work correctly.
Ionic info gives me the following information:
![image](https://user-images.githubusercontent.com/19423390/32426208-e9709d9c-c2e2-11e7-90ac-900f007afeca.png)
My package.json is following^
 "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/compiler-cli": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "ionic2-calendar": "^0.3.6"

P.S. i did update ionic-angular because I needed some plugin that required  angular/common: "4.4.6"

**Comment by twinssbc** [comment]
@Hermiona I can't see your dependencies pasted in the description.
Could you try it in a brand new Ionic project? Normally such issue is caused by a partial upgrade. For example, you updated ionic-angular but some other indirect dependencies are not updated. 
Also is there any error printed in the console?

**Comment by Hermiona** [comment]
Thanks. I created a new project and installed ur Calendar component and it worked
