### ISSUE TITLE
Faster swipe recognition

### ISSUE THREAD

**Issue by FallenRiteMonk** [twinssbc/Ionic2-Calendar#231]
Would I't be possible to fire the onRangeChanged event upon a ionSlideWillChange event of the ion-slides instead of the ionSlideDidChange event? I asking this because I load my events on the onRangeChanged event and it takes some time until they appear due to this being fired after the sliding has completed. 

I'm not exactly shore if this is possible without braking anything and on how far it would improve the loading performance of the events due to lack of in depth knowledge of this lib.

If it does break the current functioning of the calendar, would it at least be possible to have a onRangeWillChange event fired once the ion-slides fires it's ionSlideWillChange event?

**Comment by twinssbc** [comment]
@FallenRiteMonk I think the problem is not related to the onRangeChanged is fired before sliding or after sliding. If you loading method is very slow, even you call onRangeChanged a bit earlier, it still doesn't help. I think you probably need to look at how to optimize your event loading. For example, could you preload events in multiple months, then you could fill the calendar with the cached events, and load more events behind scenes. Or if you have many events need to be loaded in one month, could you only load part of them, because the mobile screen is just that big, it can't display too many events at the same time. You could provide some detail page to further display more events on a particular day. If the loading time can't be reduced, you could also consider add some loading mask to the page.

**Comment by FallenRiteMonk** [comment]
@twinssbc you might be right that firing the onRangeChange before sliding doesn't make that big of a difference, but I'm sure that the problem isn't on my slow loading. I know that because I load all my events from a cache. Further more, if I change the month programmatically (settings currentDate) the events popup immediately without the delay that appears to be when sliding.

While writing this I was playing around with my calendar implementation to better describe whats happening and I noticed the the initial month doesn't have this problem when returning to it from the previous month. To reproduce:
1) Open the calendar and wait until it has loaded and shows events (events should be loaded for previous and next month to). Ex.: November is displayed (Events for October and December are preloaded)
2) Swiping to December and back: during both swiping animations the days of the next/previous month appear blank and after animation finish the events appear with a small delay.
3) Swiping back to October behaves the same.
4) But once swiping to November again I can already see the days with events colored during the animation. This is only the case when I return to the initial month from the past, no matter how far I go back.

Is there any possibility to share a video on github? then I could show you exactly what I mean

**Comment by twinssbc** [comment]
@FallenRiteMonk I followed your steps but not able to reproduce it. You could just upload a video somewhere and paste the link here.

**Comment by FallenRiteMonk** [comment]
https://photos.app.goo.gl/QVvHfagpFFays8W03

On the last swipe you can see that the days are already blue during the swipe animation compared to the rest

**Comment by twinssbc** [comment]
@FallenRiteMonk I still can't reproduce it. I wonder could you reproduce it using the Demo page?
Have you done any customization of the calendar?

**Comment by FallenRiteMonk** [comment]
@twinssbc that might be the problem: I have a custom template for  'monthviewDisplayEventTemplate' maybe there is no delay in loading the events, but a delay in loading the costume template. I have done more changes to my custom template that also changed the heights of the day field in the calendar and the animation doesn't reflect that.

Could it be that the slides currently not showing don't use the custom template?

I'll try to recreate it in a demo and let you know

**Comment by twinssbc** [comment]
The slides not showing are using a separate template, monthviewInactiveDisplayEventTemplate.
So it should not cause any problem if you just customize monthviewDisplayEventTemplate.

Although there's one thing I need to point out, take a look at the "Known Issue" section in README. If you swipe right 3 times, you will notice this behavior, because the first slide is cached internally. But I don't know if you triggered this behavior, as you are just swiping back and forth.

**Comment by FallenRiteMonk** [comment]
@twinssbc I'm sorry I totally missed monthviewInactiveDisplayEventTemplate. That actually fixed my problem and I now only have the problem you mentioned in the "Known issues" section.

Hopefully this issue can be fixed somehow soon, but as for this issue it can be closed. Thanks for your help!
