### ISSUE TITLE
Method to access Range [Feature]

### ISSUE THREAD

**Issue by Maraket** [twinssbc/Ionic2-Calendar#243]
A simple way to retrieve the range of dates visible.

**Comment by twinssbc** [comment]
@Maraket You will get the startTime and endTime from onRangeChanged method.

**Comment by Maraket** [comment]
That is true, but I have methods which are acting outside of that method, and though I could store that in interim variables within the object, it presents additional things I need to manage (I know I am lazy :P) but more seriously, it seems odd that I  wouldn't be able to access as much information from an instance of the object

**Comment by twinssbc** [comment]
@Maraket I don't want to expose too much information by using an instance method. There are two reasons:
1. As soon as I expose the internal information, I won't be able to change it easily, as it will break the existing user.
2. The instance method can return different result at the different time you call it. I can make sure the startTime and endTime is accurate when onRangeChanged method is called, but I can't promise the value returned by an instance method, what if it is in transition from one month to another.

Since you know the currentDate of the calendar and the calendar mode, you could even calculate the range by yourself.
