### ISSUE TITLE
Events wont show up on iphone

### ISSUE THREAD

**Issue by terminaltor** [twinssbc/Ionic2-Calendar#321]
Hey,
When I use ionic serve or ionic lab I can see the events in the calendar, but when I load my app on a real device (iPhone X if it matters), no events shown.
Any suggestions?

**Comment by twinssbc** [comment]
@terminaltor There could be multiple reasons.
1. How do you get the events? Maybe the event loading method doesn't work in your real device. For example, some permission issue preventing loading data from local file system.
2. Some date format method is not supported in ios browser
https://stackoverflow.com/questions/5324178/javascript-date-parsing-on-iphone

You could also use your browser to remote debug the app in your iPhone, see if any error message printed out in the console.

**Comment by Ahmadre** [comment]
@terminaltor:
I know what your problem is: iOS devices doesn't support the same date formats as browser or android devices! You have to use moment.js and work fully with that, otherwise you won't get the correct dates there! That is because the javascript Date isn't supported cross platform!

Change every date manipulations etc. with moment!!!

I solved it like that on my IPhone. And if you have UTC-Dates, be aware of JS Dates!
