### ISSUE TITLE
Disable Previous days in other than month view

### ISSUE THREAD

**Issue by mowaiskalam** [twinssbc/Ionic2-Calendar#324]
Hello @twinssbc, First of all, thanks for the great work. It's helping me a lot in my project. 

I need to know, is there any way to disable days in 'Week View', `markDisabled` is working fine in 'Month View' but I want to disabled previous days in other views as well.

Thanks

**Comment by twinssbc** [comment]
@mowaiskalam The markDisabled has some slightly different effect between monthview and weekview.
You still be able to get if a time is disabled or not in onTimeSelected function.
In monthview, you will see the disabled date is grey, but weekview doesn't have this effect.
This is because in monthview, there are only 42 dates need to calculate the disabled state. But in weekview, there are much more time slots. So markDisabled is only triggered when you select a time slot in weekview.
If you want to achieve some grey background on weekview, you could use weekviewNormalEventSectionTemplate option.

**Comment by mowaiskalam** [comment]
@twinssbc Hi, Thanks for the reply. Yes, you are correct i need to achieve same grey background on weekview. 
I will use `weekviewNormalEventSectionTemplate` and let you know if it's works fine for me.

Thanks
