### ISSUE TITLE
Events in day and week view view always shows half an hour less

### ISSUE THREAD

**Issue by KishoreRadhakrishna** [twinssbc/Ionic2-Calendar#337]
All the events in day and week view always show 30 min less. For example if I have a event from 2:00 to 3:00, event will be displayed only on 2:00 to 2:30. Anyways when I select the event I get to see correct end time. I am using custom views for both the views.

 <ng-template #templateday let-displayEvent="displayEvent">
    <div class="calendar-event-inner" [ngClass]="getCustomClass(displayEvent.event.jobCategoryId)">{{displayEvent.event.title}}</div>
</ng-template>

<ng-template #templateweek let-displayEvent="displayEvent">
  <div class="calendar-event-inner" [ngClass]="getCustomClass(displayEvent.event.jobCategoryId)" >{{displayEvent.event.title}}</div>
</ng-template>

**Comment by twinssbc** [comment]
@KishoreRadhakrishna What kind of class do you return from the getCustomClass? Any special style applied on it?

**Comment by KishoreRadhakrishna** [comment]
@twinssbc I have just over written 'calendar-event-inner' class. All I wanted is dynamic background color depending on the  category. But if I write another, I would get just 15 min block irrespective of time duration. So I over written the class the class as below. Anyways, even if I remove custom template, the event display is 30 min less.

getCustomClass(someParameter) {
        return 'category' + someParameter;
    }

 .category4{
        background-color: rgba(153, 153, 255, 0.25);
        overflow: hidden;
        color: rgb(17, 14, 14);
        height: 100%;
        width: 100%;
        padding: 2px;
        line-height: 15px;
            }

**Comment by twinssbc** [comment]
@KishoreRadhakrishna Yes, I think this is the side effect that you set custom template.
By default, the calendar-event-inner is decorated by _ngcontent-c0, which is to inline the style within the component scope.

Generated HTML
```
<div _ngcontent-c0 class="calendar-event-inner">Event - 18</div>
```
Generated CSS
```
.calendar-event-inner[_ngcontent-c0] {
overflow: hidden;
background-color: #3a87ad;
color: white;
height: 100%;
width: 100%;
padding: 2px;
line-height: 15px;
}
```

But with your template, the HTML becomes as below, so the style can't be applied to it.
```
<div class="calendar-event-inner category4" ng-reflect-klass="calendar-event-inner" ng-reflect-ng-class="test">Event - 29</div>
```

If you add _ngcontent-c0 in the template, it will work again. But the problem is this _ngcontent-c0 is auto generated, can't promise it won't be changed in the future.
```
<ng-template #templateday let-displayEvent="displayEvent">
<div _ngcontent-c0 class="calendar-event-inner" [ngClass]="getCustomClass(displayEvent.event.jobCategoryId)">{{displayEvent.event.title}}</div>
```

So I suggest you could either add styles only applies to calendar-event-inner class without inline decorator. Or add the styles to your category class.
