### ISSUE TITLE
Change color of all day event 

### ISSUE THREAD

**Issue by KishoreKoushik** [twinssbc/Ionic2-Calendar#342]
Hi. I want to change the color of all day event in week view and also have a different color background in month view whenever there is a all day event. And also I observed the only half of the cell is coloured. I want it to be occupied entire cell.  How can I do it? I tried with the custom templates in the ReadMe document with no success. I could only do it for day view. Can you please help me doing this. Where should I place my custom class in both the views. Below is the css class I used for day view.

 .alldayeventindayview{
        overflow: hidden;
        background-color: #ffc0cb;
        color: white;
        height: 220%;
        width: 100%;
        padding: 2px;
        line-height: 15px;
    }

**Comment by twinssbc** [comment]
@KishoreKoushik Is the background color in weekview fixed?
If so, you could simply override the css style for the weekview related css class.
```
.weekview-allday-content-table .calendar-event-inner {
  background-color: red !important;
}
```

Monthview is a bit complicated, because you need different background color based on the events on that day.
You could use below template. Then implement your logic in getCustomClass method to determine the css class based on the events.

```
        <ng-template #template let-view="view" let-row="row" let-col="col">
            <div [ngClass]="getCustomClass(view.dates[row*7+col].events)">{{view.dates[row*7+col].label}}
        </ng-template>

        <calendar ... [monthviewDisplayEventTemplate]="template"></calendar>
```

**Comment by KishoreKoushik** [comment]
@twinssbc Thanks for the solution. But if I try with the above solution, for month view, I am getting the color as the background colour only for the number. It is always surrounded by blue always. I want it to full same, with the same color. How can I make it. And in the week view, the background is aplied only for the half. Even there I want it it to be full cell. I have attached images of both the views
<img width="212" alt="calebar week" src="https://user-images.githubusercontent.com/22149302/41188524-34d055e6-6bdc-11e8-9f70-a3e265db37b8.png">
<img width="212" alt="calenadar" src="https://user-images.githubusercontent.com/22149302/41188525-3cf85278-6bdc-11e8-8d8f-f3dc793ffc75.png">

**Comment by twinssbc** [comment]
@KKishoreKoushik The problem in monthview is because the div surrounding your div has the padding set to 8px and background set to blue. You could override the style of that div, for example,
```
.monthview-datetable td.monthview-primary-with-event {
  padding: 0 !important;
  background-color: transparent !important;
}
```
You also need to set the margin of your div to 8px, otherwise the total height will be different.

The problem in weekview is because by default the height of all day event is 25px, and the all day event table is 50px, so it occupies half of the space. Note that there could be more than 1 all day event per day. If you really want each all day event has 50px height, you could also override the style like below
```
.weekview-allday-content-table .calendar-event {
  height: 50px !important;
}
```

**Comment by rajkishoreandia** [comment]
could u give me getCustomClass() snippet

**Comment by twinssbc** [comment]
@rajkishoreandia The logic of getCustomClass depends on your scenario.
For example, if each event has an eventType field, below sample returns the eventType of the first event on that day.
```
function getCustomClass(events) {
  if(events.length > 0) {
    return events[0].eventType;
  }
  return '';
}
```

**Comment by JuniorFlorentino** [comment]
how to change the selected event, can not, already tried in css, ts and nothing works.


    <ng-template #template let-view="view" let-row="row" let-col="col">
        {{view.dates[row*7+col].label}}
    </ng-template>
   
    <p>
      
        <calendar
            [monthviewDisplayEventTemplate]="template"
            [eventSource]="eventSource" 
            [calendarMode]="calendar.mode"
            [showEventDetail]="calendar.showEventDetail" 
            [allDayLabel]="calendar.allDayLabel"
            [noEventsLabel]="calendar.noEventsLabel" 
            [currentDate]="calendar.currentDate"
            (onCurrentDateChanged)="onCurrentDateChanged($event)" 
            (onEventSelected)="onEventSelected($event)"
            (onTitleChanged)="onViewTitleChanged($event)" 
            (onTimeSelected)="onTimeSelected($event)" 
            step="30">
            
        </calendar>
        <ion-button expand="full" (click)="criaReserva()" class="btn_salvar">Realizar Reserva</ion-button>




ts



 changeDateAndAddAtCalendar(datas) {
        // data ="15/01/2017";
        let events = [];
        for (var i = 0; i < datas.length; ++i) {
            // code...
            let day = datas[i].DATA.substring(0, 2);
            let month = datas[i].DATA.substring(3, 5);
            let year = datas[i].DATA.substring(6);


            month--;
            let startTime = new Date(Date.UTC(year, month, day));
            day++;
            let endTime = new Date(Date.UTC(year, month, day));

            events.push({
                title: 'Reservado: ' + datas[i].UNIDADE,
                startTime: startTime,
                endTime: endTime,
                allDay: true,
                color: 'danger'
            
            });
        }

        this.eventSource = events;
    }    	//0000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by twinssbc** [comment]
@JuniorFlorentino When is this changeDateAndAddAtCalendar method being triggered? Could you try just adding some dummy event, instead of using the datas to construct an event, see if it works?
Also I don't quite get "change the selected event", how do you want to change? Basically the calendar display all events in the eventSource array, if you construct the eventSource array properly, the events will be displayed in the calendar. You could refer to the Demo page to see how it works.

**Comment by JuniorFlorentino** [comment]
would be to change the color of the day that is selected, to put a red color but it doesn't work.

**Comment by twinssbc** [comment]
@JuniorFlorentino If you just want to change the selected date color, you could add style to monthview-selected class. It is applied to the selected cell automatically.
