### ISSUE TITLE
On Date Click show day view 

### ISSUE THREAD

**Issue by timepass-ok** [twinssbc/Ionic2-Calendar#360]
Hi,
1. I want to remove event show under month calendar how do i do this? 
  <calendar showEventDetail = false></calendar> -> not working  
2.On Date Click show day view 
 onTimeSelected(ev) {
     this.calendar.mode = 'week';
}
this function  is executed directly without clicking date means default view is now week 
how do i display week on select date 
3.Month view i wanted show total number of events in particular date block

**Comment by twinssbc** [comment]
@shashical 
1. To hide the event detail section, you could set showEventDetail option to false.
2. The onTimeSelected is triggered at the first time calendar loads, because by default, the current date is selected. You could either set autoSelect to false, so that it doesn't select a date when calendar loads, or in your onTimeSelected method, you use some flag to detect if it's the first time loading and skip setting the calendar.mode to week.
3. You could use monthviewDisplayEventTemplate option to apply custom view to each date in month view.
