### ISSUE TITLE
Programmatically calling currentDate to switch to next or previous month has a conflict in slide.

### ISSUE THREAD

**Issue by jayzyaj** [twinssbc/Ionic2-Calendar#379]
I implemented two buttons in top of the calendar where each button has a `previousMonth() `method and `nextMonth()` method. When I click this two buttons it will trigger this method depending on when month to navigate if it is previous or next. Here is the code below of the two methods.

```
nextMonth() {
    this.calendar.currentDate = moment(this.calendar.currentDate).add(1, 'month').toDate()
  }

  previousMonth() {
    this.calendar.currentDate = moment(this.calendar.currentDate).subtract(1, 'month').toDate()
  }
```

However I still want to use the swipe to left or to right event where it can display the previousMonth or nextMonth but when I try to swipe to the nextMonth for example from September to October and after that I try to click the button to trigger the nextMonth() method programmatically it didn't go to November it still goes through October which suppose to be November the nextMonth it still remains the sameMonth when I swiped

**Comment by twinssbc** [comment]
@jayzyaj I think the reason is because you are using below syntax to bind to the currentDate attribute.
```
        [currentDate]="calendar.currentDate"
```

Notice that this is one-way binding, if you change calendar.currentDate, it will change the calendar's internal _currentDate variable. But when you swipe to the next month, although the internal variable is changed, it won't change the calendar.currentDate variable.

You need to register the onCurrentChanged method, and set the calendar.currentDate when it is triggered.
```
<calendar ... (onCurrentDateChanged)="onCurrentDateChanged($event)"></calendar>
onCurrentChanged = (ev: Date) => {
            this.calendar.currentDate = ev;
        };
```

**Comment by jayzyaj** [comment]
@twinssbc  Thank you! Not it is working
