### ISSUE TITLE
Building next month view in advance before swiping end

### ISSUE THREAD

**Issue by chanphillip** [twinssbc/Ionic2-Calendar#40]
In month view, when swiping to the next/previous month, before releasing the cursor/finger and the next/previous is visible, the classes (.text-muted, .monthview-disabled) are not properly applied to those dummy slides.
Which means before releasing the cursor/finger, the layout shown is not visually correct.

**Comment by twinssbc** [comment]
@chanphillip When I designed this calendar, I referred to some native calendar app, they all have the same behavior. Only renders the current slide, but the next/previous slide is just placeholder for animation purpose. It could also reduce some calculation to improve the performance.

**Comment by chanphillip** [comment]
@twinssbc Ok I get it. I agree it is native to load only the events on the current slide.
But for styles like .text-muted & .monthview-disabled, I would see them as a part of the calendar layout so I would expect that. And I think it will not affect the performance much.
Now every time you swipe, the font colors are flashing momentarily which is a little annoying.

**Comment by tobika** [comment]
@chanphillip hello and thanks for this good component.

Do you plan to implement the update of non visible month views before swiping? I think it could be a big gain for the user. I am using a custom template for the month view so after each swipe the calendar view changes quite a bit. Would be great to have such an improvement. If I understand the code better I might try it myself :)

**Comment by twinssbc** [comment]
@tobika I think the really problem is your custom template displayed for the current month view is different from the default view in the non visible months?
In this case, I will expose a custom template option for the non visible months.

**Comment by tobika** [comment]
@twinssbc yes that's right, thanks a lot, would be great to have this other template exposed.

**Comment by tobika** [comment]
@twinssbc I checked out the code a bit and see that for every slide you have 2 month views. One that is shown when the view is active, the other one is shown during sliding process. 
Is there a reason you did it like this? I just deleted the duplicate slides for a test and don't notice anything wrong. Just that the different template problem has gone away.

Also performance wise this is nice because there are much less DOM nodes in the component to update.
As you said in the Readme there is still the problem with every 3rd scroll having a cached slide but this is another thing I guess.

But maybe I forget something really important :)

**Comment by twinssbc** [comment]
@tobika 
May I know which slide is duplicate?
If I don't have 2 month views for every slide, how to switch different views in active and inactive mode?
Since ngIf won't actually add any DOM element if the condition check is false, so the total DOM nodes that are tracked are always limited to three month views, instead of six.

**Comment by tobika** [comment]
@twinssbc 
ah yes, it is true that you don't have more DOM elements, but you have to re-render them when you switch between inactive month and active month view.

Do you really have to switch the views between active/inactive? Maybe I just don't get something here but for me it seems to work the same since I have deleted the inactive view. The component just uses the active view which is the same as the inactive except you don't use the template. Less DOM manipulation.

But as I said, maybe I forget something important :)

**Comment by twinssbc** [comment]
@tobika 
There are less elements in the inactive view.
For example, in the month view, there's a getHighlightClass method applied to each cell in the active month. If I also make the inactive view having this method, then the getHighlightClass will be called 3 times as before, while it's not necessary to apply style on the cells of inactive month.

**Comment by twinssbc** [comment]
@tobika I have added monthviewInactiveDisplayEventTemplate option in version 0.2.5.

**Comment by tobika** [comment]
@twinssbc thanks a lot for this :) I guess we can close this issue?
