### ISSUE TITLE
Show only in calendar the interested months

### ISSUE THREAD

**Issue by kevinpallado** [twinssbc/Ionic2-Calendar#408]
Hi,

Is it possible to display the specific months in the calendar? For example like I just want to get from January to March only. Do you have any support for this kind of action?

**Comment by kevinpallado** [comment]
@twinssbc uhm, how can I use the `[lockSwipeToPrev]="lockSwipeToPrev"` properly, when the month changes while I am putting new activity in every month the accessible month will become on a single month. Hoping for you feedback

**Comment by kevinpallado** [comment]
@twinssbc  so after I added an activity (dismissing the activity modal page) I got this [error](https://imgur.com/a/fdMjhar) I dont know what is the reason. The thing is I am not navigating another page I am just adding layer component, I hope you can see this and suggest what to do

**Comment by twinssbc** [comment]
@kevinpallado So Angular is doing double check in its rendering lifecycle. This error means the value is changed since last check. It usually happens when you want to set some value before the whole rendering lifecycle completes. What I usually do is to use setTimeout to delay the operation after the rendering. Something like this:

```
        let me = this;
        setTimeout(function() {
            me.lockSwipes = true;
        },0);
```
