### ISSUE TITLE
Replace WeekView/DayView Template Without Losing It's Sliding Function

### ISSUE THREAD

**Issue by StevenMitrais** [twinssbc/Ionic2-Calendar#448]
![Capture](https://user-images.githubusercontent.com/44386841/60002451-3e402800-969b-11e9-9192-cec4e2b0d870.JPG)

Hai @twinssbc ,
At first I wanna thank you for this awesome library.

I just wonder whether if i can totally modify default weekview/dayview and retrieving It's data without losing the sliding function, then use the data like above images.

The images above is an example, but It wasn't using default weekView template, so there's no sliding function right there

Thank You

**Comment by twinssbc** [comment]
@StevenMitrais If you check **View Customization** Option in README, there are some customization templates for week view and day view. But for the screenshot you provided, IMO, it is probably easier to implement your own page. Because there are a lot of logic is designed for the current layout, such as how to place each event in which column and row. If you just want to display it as a list, it's not worth to customize based this calendar.

**Comment by StevenMitrais** [comment]
Yes I think you're right.
I just found a way using ion-card looped inside ion-slide to achieve that
But still has some problematic UI issue

Thanks a Lot

**Comment by SathishS90** [comment]
@StevenChandra, @twinssbc  can you share the code, i need to work on the week view and day view templates to be shown in good shape, in default view, am adding more than 10 events in a day its scattered, would be helpful, if got a template, need help

![DayView](https://user-images.githubusercontent.com/42955364/104267330-6b3f7000-54b7-11eb-8768-1c42716b4cbc.JPG)
![weekview](https://user-images.githubusercontent.com/42955364/104267335-6e3a6080-54b7-11eb-915a-a1c068d67192.JPG)
