### ISSUE TITLE
Ionic 6 Angular 13 swiping problem

### ISSUE THREAD

**Issue by YSFKBDY** [twinssbc/Ionic2-Calendar#663]
I've installed the calendar to my App, and working fine. But, when I swipe to next month, (let's say current month is october), calendar shows current month's days every third swipe, no matter what month we are at until I stop dragging/touching. When I stop dragging/touching, days are come back to normal and shows days of month you at. Same thing occurs backwards, too. It's really annoying.

**Current month:**
![image](https://github.com/twinssbc/Ionic2-Calendar/assets/27686947/dc111a80-2cb4-4177-8f87-aa71e01c842b)

**While swiping to right (you can see days of october, instead of january):**
![image](https://github.com/twinssbc/Ionic2-Calendar/assets/27686947/0024f168-7845-48d4-a85d-212a5c4b9995)

**After swiping complete (Days back to normal): **
![image](https://github.com/twinssbc/Ionic2-Calendar/assets/27686947/034943de-1558-48a6-89ec-60c2ee512f88)

**Comment by twinssbc** [comment]
Yes, this is the behavior of old slider component version, it uses 3 looped slides to keep updating for the previous, current, next month. The old version caches the prev and next slide, that's why in the middle of the swiping, it won't be updated, only when the swiping is over. You could upgrade to the latest version, that behavior is eliminated.

Version 2.1.x depends on Ionic (>=7.0.0), Angular (>=16.0.0) and Swiper (>=10.1.0).

**Comment by YSFKBDY** [comment]
We are using Ionic 6, so I can't upgrade to the latest version. Thank you for your explanation.
