### ISSUE TITLE
Angular 2 module support

### ISSUE THREAD

**Issue by jayh92** [twinssbc/Ionic2-Calendar#7]
I'm looking to pull this into an Ionic2 application using Angular2 final; however, this library only exposes itself as a Directive, which can no longer be declared on a Component directly. Are there any plans of supporting this soon?

**Comment by mfalzetta** [comment]
I have the same.

[18:58:43]  ngc error: Error: Template parse errors:
Can't bind to 'eventSource' since it isn't a known property of 'calendar'. ("
  <ion-label style="padding-left: 5%;"><b>{{mounth}} / {{year}}</b></ion-label>

  <calendar [ERROR ->][eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [(currentDate)]="c"): FaltaComponent@11:12
Can't bind to 'calendarMode' since it isn't a known property of 'calendar'. ("

  <calendar [eventSource]="eventSource"
            [ERROR ->][calendarMode]="calendar.mode"
            [(currentDate)]="calendar.currentDate"
            (onRang"): FaltaComponent@12:12
Can't bind to 'currentDate' since it isn't a known property of 'calendar'. ("
  <calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [ERROR ->][(currentDate)]="calendar.currentDate"
            (onRangeChanged)="reloadSource(startTime, endTime)"): FaltaComponent@13:12
'calendar' is not a known element:
1. If 'calendar' is an Angular component, then verify that it is part of this module.
2. If 'calendar' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
  <ion-label style="padding-left: 5%;"><b>{{mounth}} / {{year}}</b></ion-label>

  [ERROR ->]<calendar [eventSource]="eventSource"
            [calendarMode]="calendar.mode"
            [(curren"): FaltaComponent@11:2
    at TemplateParser.parse (/Dropbox/MFalzetta/Projetos-Dev/4CDigital/SmartNote/smartnote-app/node_modules/@angular/compiler/bundles/compiler.umd.js:8502:21)
    at OfflineCompiler._compileComponent (/Dropbox/MFalzetta/Projetos-Dev/4CDigital/SmartNote/smartnote-app/node_modules/@angular/compiler/bundles/compiler.umd.js:13024:53)
    at /Dropbox/MFalzetta/Projetos-Dev/4CDigital/SmartNote/smartnote-app/node_modules/@angular/compiler/bundles/compiler.umd.js:12976:109
    at process._tickCallback (node.js:369:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by twinssbc** [comment]
OK, I will take a look.

**Comment by mfalzetta** [comment]
Hi @twinssbc 

Do you have a expected start for development?

Regards.

**Comment by twinssbc** [comment]
@mfalzetta 
Yes, I have started working on it.
Since I need to merge a big PR at the same time, so it will take a bit longer.

**Comment by twinssbc** [comment]
@mfalzetta I have published the version 0.0.8 which depends on Angular 2.0.0 and Ionic 2.0.0.rc.1.
Feel free to have a try. Thanks.
