### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by gdesplin** [twinssbc/Ionic2-Calendar#74]
I've been trying to implement this calendar, however I'm having a hard time simply creating an event. The readme doesn't explicitly give a good 'quick start' type example. The demo just creates random events, which isn't really helpful. Could I get an example of how to create a new event on time click pre filling with the time and/or also without a time click, like on a button.  Thanks.

**Comment by twinssbc** [comment]
@gdesplin The way to generate an event is out of the scope of this calendar. Because users have different ways, for example, when a time is clicked, it will navigate to another page to ask user to fill a form; or directly query a database to fetch the event.
What the calendar cares is only the eventSource object, once it's changed, the view will be updated.

In the demo, the way to modify the eventSource object is when you click the "Load" button.
You can simply move the logic to the onRangeChanged callback, if you want to load events when navigating between months or move it to the onTimeSelected callback, if you want to load events when clicking a time.
