### ISSUE TITLE
Calendar crashes when switching fast between views

### ISSUE THREAD

**Issue by Daskus1** [twinssbc/Ionic2-Calendar#75]
When I switch fast between dayview and weekview for a few times the whole calendar crashes and the app needs to be started again.

The following exception is thrown:
`EXCEPTION: Error in ./WeekViewComponent class WeekViewComponent - inline template:174:12 caused by: Cannot read property 'length' of undefined`.

I could also reproduce this on the demo app.

**Comment by twinssbc** [comment]
@Daskus1 
This seems a defect in the Swiper code which Ionic slide depends on.
According to below code snippet, when you quickly switch to another view, the _slides hasn't been initialized, that's why undefined error is thrown.
https://github.com/driftyco/ionic/blob/master/src/components/slides/swiper/swiper.ts

```
function destroyLoop(s: Slides) {
  eachChild(s._wrapper, '.' + CLS.slide + '.' + CLS.slideDuplicate, ele => {
    ele.parentElement.removeChild(ele);
  });
  for (var i = 0; i < s._slides.length; i++) {
    s._slides[i].removeAttribute('data-swiper-slide-index');
  }
}
```

I will submit a PR to Ionic team.
As a short term workaround, you can add an "undefined" check in your installed Ionic source code.

**Comment by twinssbc** [comment]
Related issue has been created
https://github.com/driftyco/ionic/issues/10830

**Comment by hamzahamidi** [comment]
A way to prevent this issue is to set a timer for the buttons:

` <button ion-button [disabled]="goodToChange" (click)="changeMode('month')">M</button>
            <button ion-button [disabled]="goodToChange" (click)="changeMode('week')">W</button>
            <button ion-button [disabled]="goodToChange" (click)="changeMode('day')">D</button>`

in your page.ts
`...`
`goodToChange:boolean`
`...`
modify the method
`changeMode(mode) {
    this.goodToChange = true
    this.calendar.mode = mode;
    this.stateChange()
  }
`
Add this method
`
  stateChange() {
    setTimeout( ()=> {
        this.goodToChange=false;
    }, 500);
  }`
